version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  etl:
    build:
      context: .
      dockerfile: etl/Dockerfile
    environment:
      API_URL: "https://jsonplaceholder.typicode.com/posts"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/posts_db"
      EXTRACT_CRON: "*/5 * * * *"
      TRANSFORM_CRON: "*/6 * * * *"
      LOG_LEVEL: "INFO"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/posts_db"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
